export default {
    HOME:"INMOBICAPITAL",
    PROFILE:"PERFIL DE USUARIO",
    LOGIN:"INICIAR",
    SIGNUP:"REGISTRO",
    ABOUT:"NOSOTROS",
    TABS:"HOME",
    COMPLETESIGNUP:"COMPLETAR REGISTRO",
    TEMPPROFILE:"USUARIOS",
    BENEFICIARIES:"BENEFICIARIOS",
    POLITICS:"POLITICAMENTE EXPUESTO",
    UPLOADER:"SUBIR MIS DOCUMENTOS",
    FORMULARIOS:"COMPLETA TU REGISTRO",
    CONTRATO:"MI CONTRATO"
}